### ISSUE TITLE
Conflicting references to download directory

### ISSUE THREAD

**Issue by wimpyprogrammer** [vsonix-bub/node-google-closure-library-latest#1]
I love this package and the idea behind it.  It solves my problem on another project of trying to keep an up-to-date copy of the Closure Library.

But I'm confused about how to put this package into action.  I see in `install.js` that the latest Closure Library is extracted into `lib`, but `index.js` is looking in `bin` for those files.  Is this just a typo, or am I missing a step to move the files from `lib` to `bin`?

Everything seems to work well when I change `index.js` to reference the `lib` directory, so I'll submit a Pull Request to that effect.

**Comment by wimpyprogrammer** [comment]
Submitted Pull Request #2.

**Comment by thebub** [comment]
Hi, sorry for the little delay. I'll take a look at your two issues today and then accept the pull requests.

**Comment by thebub** [comment]
I accepted your pull request #2  and released a new version 0.2.0. It should be available over npm soon. Thanks.
