### ISSUE TITLE
Asynchronous functions causing setup to fail

### ISSUE THREAD

**Issue by wimpyprogrammer** [vsonix-bub/node-google-closure-library-latest#3]
I'm using the `google-closure-library-latest` package as a dependency for a different package that invokes GCL in a `postinstall` hook.  This means that:
1. downloading the Closure library,
2. extracting it,
3. creating its destination folder, and
4. copying the Closure library to its destination

are occurring right after each other.

I'm encountering issues because steps 2 and 3 are asynchronous, so step 4 tries to run before everything is ready.  I'll submit a couple Pull Requests with the fixes I've made.

**Comment by thebub** [comment]
I accepted your pull requests #4 , #5 and released a new version 0.2.0. It should be available over npm soon. Thanks.

I am also thinking about changing the install function, to use a synchronous folder copy implementation.

**Comment by wimpyprogrammer** [comment]
Great, thanks!  Everything is working wonderfully with the changes above.

In my case the `ncp` call isn't a problem because it's the last thing to run, so nothing in the setup chain depends on it.  But other users may have need of a synchronous folder copy.
